on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.8.3"
      - name: Install dependencies
        run: poetry install --no-root -n
      - name: Lint
        run: |
          poetry run ruff check
          poetry run flake8 .
          poetry run poe pylint --output-format=junit --extra='--output=pylint_results.xml'
      - name: Test
        run: |
          poetry run pytest --dead-fixtures --suppress-no-test-exit-code
          poetry run pytest --suppress-no-test-exit-code
