name: lint
on: [push]

env:
  UV_LOCKED: "true"
  UV_LINK_MODE: copy

jobs:
  repository-lint:
    runs-on: ubuntu-24.04
    container: ghcr.io/astral-sh/uv:0.6.2-python3.12-bookworm-slim@sha256:dd20c7312c1b0f77a18cd9b0e88d238997d6faab99cc9abc43d006945716c505
    if: github.ref_name != github.event.repository.default_branch
    steps:
      - name: Install git
        run: |
          apt-get update && apt-get install -qq git
          git config --global --add safe.directory /__w/grimoire/grimoire
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history
      - name: Check commits
        run: uv run cz check --rev-range origin/${{ github.event.repository.default_branch }}..${{ github.sha }}
  python-lint:
    runs-on: ubuntu-24.04
    container: ghcr.io/astral-sh/uv:0.6.2-python3.12-bookworm-slim@sha256:dd20c7312c1b0f77a18cd9b0e88d238997d6faab99cc9abc43d006945716c505
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint code
        run: |
          uv run poe types
          uv run poe pylint --output-format=junit --extra='--output=pylint_results.xml'
      - name: Upload pylint results
        uses: actions/upload-artifact@v4
        with:
          name: pylint_results.xml
          path: pylint_results.xml
