name: test
on: [push]

env:
  UV_LOCKED: "true"
  UV_LINK_MODE: copy

jobs:
  pytest:
    runs-on: ubuntu-24.04
    container: ghcr.io/astral-sh/uv:0.6.2-python3.12-bookworm-slim@sha256:dd20c7312c1b0f77a18cd9b0e88d238997d6faab99cc9abc43d006945716c505
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run pytest
        run: uv run poe test
      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage.xml
          path: coverage.xml
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: junit.xml
          path: junit.xml
